config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  get 'imageupload/index'

  get 'imageupload/new'

  get 'imageupload/create'

  get 'imageupload/destroy'

    resources :users
  
  resources :likes
  resources :companies

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :user
	has_many :likes
	mount_uploader :logo, AttachmentUploader
end
	

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :verify_is_admin, only: [:edit, :destroy]

  # load_and_authorize_resource
  # GET /companies
  # GET /companies.json 
  def index
    companies = Company
    filters = [:name]
    filters.each do |filter|
      if params.has_key?(filter.to_s)
        companies.where(filter.to_s => params[filter])
      end
    end
    @companies = companies.limit(10)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }    

      
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :geography, :hyperlocal, :commission, :category, :delivery, :logo)
    end

    def verify_is_admin
      (current_user.nil?) ? redirect_to(companies_path) : (redirect_to(companies_path)) unless current_user.admin?
    end 

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :geography %><br>
    <%= f.text_area :geography %>
  </div>
  <div class="field">
    <%= f.label :hyperlocal %><br>
    <%= f.check_box :hyperlocal %>
  </div>
  <div class="field">
    <%= f.label :commission %><br>
    <%= f.text_field :commission %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_area :category %>
  </div>
    <div class="field">
    <%= f.label :delivery %><br>
    <%= f.check_box :delivery %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mobile-first C2C Marketplaces</h1>

<!-- start rank html -->


<div class="rank_by_name">
  Filter by Name
  <div>
    <%= select_tag :name, options_for_select(Company.uniq.pluck(:name)) do %>
      <% @companies.each do |company| %>
          <%= company.name %>
      <%end%>
    <% end %>
  </div>  
</div>

<div class="rank_by_geography">
  Filter by Geography
  <div id="tag_geography"> 
    <%= select_tag :geography, options_for_select(Company.uniq.pluck(:geography)) do %>
      <% @companies.each do |company| %>
          <%= company.geography %>
      <%end%>
    <% end %>

  </div>  
</div>

<div class="rank_by_hyperlocal">
  Filter by Hyperlocal  
  <div id="tag_hyperlocal">
    <%= select_tag :hyperlocal, options_for_select(Company.uniq.pluck(:hyperlocal)) do %>
      <% @companies.each do |company| %>
          <%= company.hyperlocal %>
        <%end%>
      <% end %>
  </div>  
</div>


<div class="rank_by_commission">
  Filter by Commission
  <div>
    <%= select_tag :commission, options_for_select(Company.uniq.pluck(:commission)) do %>
      <% @companies.each do |company| %>
       <%= company.commission %>
      <%end%>
    <% end %>
  </div>  
</div>


<div class="rank_by_category">
  Filter by Category
  <div>
    <%= select_tag :category, options_for_select(Company.uniq.pluck(:category)) do %>
      <% @companies.each do |company| %>
          <%= company.category%>
      <%end%>
    <% end %>
  </div>  
</div>

<div class="rank_by_delivery">
  Filter by Category
  <div>
    <%= select_tag :delivery, options_for_select(Company.uniq.pluck(:delivery)) do %>
      <% @companies.each do |company| %>
          <%= company.delivery%>
      <%end%>
    <% end %>
  </div>  
</div>

<br>


<form>
<input id="refresh_button" TYPE="button" onClick="history.go(0)" VALUE="Refresh Filters">
</form>


<br>
<br>
<br>



<!-- end rank html -->

<!-- start database html -->


<div class="flex-table">
 
  <div class="database_table_body">
    <% @companies.each do |company| %>
     <%= div_for company, :class => "large_rowBox" do %>
      <div id="database_body">
        <div class="database_table_image">
          <%= image_tag(company.logo_url, width:90, height:70) %>
        </div>
           <%= div_for company, :class => "rowBox" do %>
        <div class="database_global"> 
          <div class="database_title">
              Name:
          </div>  
          <div id="name" class="database_input" data-name="<%= company.name %>">
              <%= company.name %>
          </div>
        </div>
        <div class="database_global"> 
          <div class="database_title">
            Geography:
          </div> 
          <div id="geography" class="database_input" data-geography="<%= company.geography %>">
            <%= company.geography %>
          </div>
        </div>
        <div class="database_global"> 
          <div class="database_title">
            Hyperlocal:
          </div>
          <div id="hyperlocal" class="database_input" data-hyperlocal="<%= company.hyperlocal %>"> 
            <%= company.hyperlocal %>
          </div>
        </div>
        <div class="database_global"> 
          <div class="database_title">
            Commission:
          </div> 
          <div id="commission" class="database_input" data-commission="<%= company.commission %>">
            <%= company.commission %>
          </div>
        </div>
        <div class="database_global"> 
          <div class="database_title">
            Category:
          </div>
          <div id="category" class="database_input" data-category="<%= company.category %>">
          <%= company.category %>
          </div>
        </div>
        <div class="database_global">
          <div class="database_title">
            Delivery:
          </div>
          <div id="delivery" class="database_input" data-delivery="<%= company.delivery %>">
            <%= company.delivery %>
          </div>
        </div>
        <div class="modify_container">
          <div class="modify">         

            <%= link_to 'Show', company %>
          </div>
          <div class="modify">

            <%= link_to 'Edit', edit_company_path(company) %></div>
          <div class="modify">
            <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div> 
        </div>
      </div>
      <% end %>
      <% end %>
    <% end %>
  </div>

</div>

<!-- end database layout -->

<br>


<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show_large_rowBox">

  <div class="show_image">
    <%= image_tag(@company.logo_url, width:90, height:70) %>
  </div>

  <div class="show_rowBox">

    <div class="show_small_rowBox">
      <div class="show_small_title">
        <strong>Name:</strong>
      </div>
      <div class="show_small_input">
        <%= @company.name %>
      </div>
    </div>

    <div class="show_small_rowBox">
      <div class="show_small_title">
        <strong>Geography:</strong>
      </div>
      <div class="show_small_input">
        <%= @company.geography %>
      </div>
    </div>

    <div class="show_small_rowBox">
      <div class="show_small_title">
        <strong>Hyperlocal:</strong>
      </div>
      <div class="show_small_input">
        <%= @company.hyperlocal %>
      </div>
    </div>

    <div class="show_small_rowBox">
      <div class="show_small_title">
        <strong>Commission:</strong>
      </div>
      <div class="show_small_input">
        <%= @company.commission %>
      </div>
    </div>

    <div class="show_small_rowBox">
      <div class="show_small_title">
        <strong>Category:</strong>
      </div>
      <div class="show_small_input">
        <%= @company.category %>
      </div>
    </div>
  
    <div class="show_small_rowBox">
      <div class="show_small_title">
        <strong>Delivery:</strong>
      </div>
      <div class="show_small_input">
        <%= @company.delivery.to_s %>
      </div>
    </div>


    <div class="show_small_rowBox" id="show_edit">
      <%= link_to 'Edit', edit_company_path(@company) %>
    </div>
    <div class="show_small_rowBox" id="show_back">
      <%= link_to 'Back', companies_path %>
    </div>

  </div>
</div>